### ISSUE TITLE
document IPv6 syntax in multiserver addresses

### ISSUE THREAD

**Issue by regular** [ssb-js/multiserver#23]
I believe they need to be escaped with square brackets?

For example:

`net:[::]:8100 ...`

**Comment by christianbundy** [comment]
That seems super reasonable to me, should we be doing this when we output via `stringify()` too? I'm not sure if that's how it currently works.

**Comment by dominictarr** [comment]
official spec for addresses is https://github.com/ssbc/multiserver-address

arguments to sub protocols are split by `:` so `[` doesn't escape them. but it works if they are included. I think if it's a ipv6 it just pops the port from the last arg, then concats the rest with `:` that means port is always required.
maybe it would be better if the format was `protocol:...` and multiserver protocols where just passed a string?
