### ISSUE TITLE
ws test failing on macos

### ISSUE THREAD

**Issue by christianbundy** [ssb-js/multiserver#61]
Brief bug report because I'm on mobile walking home. Spent a few hours today debugging why the Travis tests on MacOS are failing and I'm very confused. I'm seeing this on the 'main' branch and also on my branch with the new Pull-WS.

We're starting a WS client and server, and then connecting to server.stringify(), but when we do the `if (err) throw err` dance we end up throwing a weird error.

The error originates from a net server on some ungodly high port, but `plugs.js` isn't listening there. Maybe the problem is caused by multiple tests running at the same time? Anyway, the problem is that we're receiving a TCP + SHS connection but the client connecting doesn't have a public key in their address. I don't know what would cause this.

Tomorrow I'll probably edit the test command so that we're only testing the one file. I'm worriee about why we'd be propagating an error from another server (race condition?), but I wouldn't be surprised.

**Comment by arj03** [comment]
Github CI now tests on mac and tests are passing for node 10, 12 & 14.
